apiVersion: v1
kind: Service
metadata:
  name: nols-products-ms
spec:
  type: NodePort
  selector:
    app: nols-products-ms
  ports:
  - protocol: TCP
    port: 3090
    targetPort: 3090
    nodePort: 8086