name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 
    # - name: Build the Docker image
    #   run: docker build products/. --file "products/Dockerfile" --tag nols-products:$(date +%s)

    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: 
          echo ${{ secrets.DOCKERHUB_USERNAME }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.1.1
      with:
        images: nmdsmartins/nols-products
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: products/.
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
