name: Products MS Push to Docker

env:
  DEPLOYMENT_VERSION: 1.0.${{ github.run_number }}

on:
  push:
    branches: [ "main" ]
    # paths:
    #   - "products/**"
    #   - "!products/deployment/**"
  # pull_request:
  #   branches: [ "main" ]
  #   paths:
  #     - "products/**"

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: nmdsmartins/nols-products
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
        tags: "1.0.${{ github.run_number }},latest"
        context: products

  deployment:

    runs-on: ubuntu-latest
    needs: build
    
    steps:
      # - uses: actions/checkout@v3
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'products/deployment/products.deployment.yml'
          propertyPath: 'spec.template.spec.containers.0.image'
          value: nmdsmartins/nols-products:$DEPLOYMENT_VERSION
          branch: main
          message: Deployment updated to versio $DEPLOYMENT_VERSION 