name: Products MS Push to Docker

on:
  push:
    branches: [ "main" ]
    paths:
      - "products/**"
  # pull_request:
  #   branches: [ "main" ]
  #   paths:
  #     - "products/**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: nmdsmartins/nols-products
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
        context: products
        tags: "latest,${{ steps.pre-step.outputs.release-version }}"
        # tag_semver: true
    # - uses: actions/checkout@v3 
    # - name: Build the Docker image
    #   run: docker build products/. --file "products/Dockerfile" --tag nols-products:$(date +%s)

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2.1.0
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
        
    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@v4.1.1
    #   with:
    #     images: nmdsmartins/nols-products
    #     run: echo ${{ steps.meta.outputs }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v3.2.0
    #   with:
    #     context: products/.
    #     push: true
    #     tags: nmdsmartins/nols-products:1.0.${{ github.run_number }}
    #     labels: ${{ steps.meta.outputs.labels }}
